### ISSUE TITLE
News Categories widget includes Pages in counts

### ISSUE THREAD

**Issue by joehobson** [navnorth/wp-oii-theme#3]
Is it possible to filter the query for the News Categories widget too, so that it only includes posts and not pages? I updated test with your latest fix (for #1) and noticed that the _i3 programs_ category shows up in the right column of the News page with a count of 3 posts, but when you click on it you get none. I'm guessing the 3 is pages and not news articles

http://oii-test.navnorth.com/category/i3-program/

**Comment by johnpaulbalagolan** [comment]
Hi Sir,

I created a copy of Categories Widget and named it "News Categories Widget". It's basically the same with Categories Widget but I altered it so that it will display only the categories that have posts. I am still checking the posts count next to the category at the moment. Please test the latest code I committed to github. 

We need to replace the Categories widget on News page to the News Categories Widget with the same settings as the former.

Thanks.

**Comment by johnpaulbalagolan** [comment]
fix #3 with latest source code committed to github. I have fixed the post count on categories display to show actual posts count excluding pages.
